import React, { useEffect, useRef, useState } from "react";
import { Bot, Send, Trash2, Wifi, WifiOff, Sparkles } from "lucide-react";
import "../styles/assistant.css";

const CHAT_KEY = "pdf-concurso-edu-ai-chat";
const OLLAMA_URL = "http://127.0.0.1:11434";
const MODEL = "qwen3:8b";
const SYSTEM_PROMPT = `Você é o assistente pedagógico do PDF Concurso EDU, especializado em concursos públicos brasileiros. Responda sempre em português brasileiro, de forma didática e objetiva. Use prioritariamente as informações fornecidas pelo usuário e pela plataforma. Não invente leis, artigos, autores, datas, gabaritos ou referências. Quando não tiver segurança, diga claramente que a informação precisa ser conferida em fonte oficial. Em questões, nunca altere o gabarito oficial informado pela plataforma; sua função é explicá-lo. Em legislação, dê preferência à terminologia legal brasileira e sinalize quando a redação vigente precisar ser conferida.`;

function readJSON(key, fallback) { try { const value = JSON.parse(localStorage.getItem(key)); return value ?? fallback; } catch { return fallback; } }

export default function AssistenteIA() {
 const [messages,setMessages]=useState(()=>readJSON(CHAT_KEY,[])); const [input,setInput]=useState(""); const [sending,setSending]=useState(false); const [status,setStatus]=useState("unknown"); const endRef=useRef(null);
 useEffect(()=>{localStorage.setItem(CHAT_KEY,JSON.stringify(messages));endRef.current?.scrollIntoView({behavior:"smooth"})},[messages]);
 useEffect(()=>{testConnection()},[]);
 async function testConnection(){try{const r=await fetch(`${OLLAMA_URL}/api/tags`);if(!r.ok)throw new Error();setStatus("online")}catch{setStatus("offline")}}
 async function sendMessage(event){event?.preventDefault();const text=input.trim();if(!text||sending)return;const userMessage={role:"user",content:text,at:Date.now()};const nextMessages=[...messages,userMessage];setMessages(nextMessages);setInput("");setSending(true);try{const response=await fetch(`${OLLAMA_URL}/api/chat`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model:MODEL,stream:false,think:false,messages:[{role:"system",content:SYSTEM_PROMPT},...nextMessages.map(({role,content})=>({role,content}))]})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error||`Erro ${response.status}`);const answer=data?.message?.content?.trim()||"A IA não retornou conteúdo.";setMessages(current=>[...current,{role:"assistant",content:answer,at:Date.now()}]);setStatus("online")}catch(error){setStatus("offline");setMessages(current=>[...current,{role:"assistant",error:true,content:error?.message||"Não consegui conectar ao Ollama. Verifique se ele está aberto neste computador.",at:Date.now()}])}finally{setSending(false)}}
 function clearChat(){if(!messages.length||window.confirm("Apagar toda a conversa com o Assistente IA?"))setMessages([])}
 return <section className="page ai-page"><div className="ai-header"><div className="ai-title-group"><div className="ai-icon"><Bot size={26}/></div><div><div className="page-eyebrow">INTELIGÊNCIA ARTIFICIAL LOCAL</div><h1>Assistente IA</h1><p>Estude, revise conteúdos e resolva questões com IA local pelo Ollama.</p></div></div><div className="ai-header-actions"><button type="button" className={`ai-status ${status}`} onClick={testConnection}>{status==="online"?<Wifi size={16}/>:<WifiOff size={16}/>} {status==="online"?"Ollama conectado":"Ollama desconectado"}</button><button type="button" className="ai-icon-button danger" onClick={clearChat}><Trash2 size={18}/></button></div></div><div className="ai-shell"><div className="ai-chat">{messages.length===0?<div className="ai-empty"><div className="ai-empty-icon"><Sparkles size={30}/></div><h2>Como posso ajudar nos seus estudos?</h2><p>Peça explicações, resumos, questões, correções, revisões e planos de estudo.</p><div className="ai-suggestions">{["Explique a LDB de forma resumida","Crie 5 questões de conhecimentos pedagógicos","Revise crase comigo","Monte um plano de estudo para hoje"].map(s=><button key={s} type="button" onClick={()=>setInput(s)}>{s}</button>)}</div></div>:<div className="ai-messages">{messages.map((m,i)=><div className={`ai-message ${m.role} ${m.error?"error":""}`} key={`${m.at}-${i}`}><div className="ai-avatar">{m.role==="user"?"DF":<Bot size={17}/>}</div><div className="ai-bubble"><strong>{m.role==="user"?"Você":"Assistente IA"}</strong><p>{m.content}</p></div></div>)}{sending&&<div className="ai-message assistant"><div className="ai-avatar"><Bot size={17}/></div><div className="ai-bubble"><strong>Assistente IA</strong><p className="ai-thinking">Analisando...</p></div></div>}<div ref={endRef}/></div>}</div><form className="ai-composer" onSubmit={sendMessage}><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendMessage(e)}}} placeholder="Pergunte sobre legislação, português, filosofia, pedagogia..." rows={2}/><button type="submit" disabled={!input.trim()||sending}><Send size={19}/></button></form><div className="ai-model-note">Motor local: <strong>Ollama · {MODEL}</strong> · Sem cobrança de API. Conteúdos legais devem ser conferidos em fontes oficiais.</div></div></section>
}
