import React,{useMemo,useState}from"react";
import{Download,ScanLine,Trophy,ShieldCheck}from"lucide-react";
import AnswerSheetScanner from"../components/simulations/AnswerSheetScanner";
import{generateAnswerSheetPdf}from"../utils/answerSheet";
import"../styles/simulados.css";
const ACTIVE="pdf-concurso-edu-active-paper-exam-v1";
const HISTORY="pdf-concurso-edu-paper-results-v1";
function load(k,fallback=null){try{return JSON.parse(localStorage.getItem(k))??fallback}catch{return fallback}}
export default function CartaoResposta(){const[read,setRead]=useState(null);const active=useMemo(()=>load(ACTIVE),[]);const[result,setResult]=useState(null);function correct(rows){setRead(rows);if(!active?.questions?.length)return;const details=active.questions.map((q,i)=>{const r=rows[i]||{};return{number:i+1,selected:r.selected??null,answer:q.answer,correct:r.selected===q.answer,status:r.status,discipline:q.officialLabel||q.discipline,topic:q.topic}});const correctCount=details.filter(x=>x.correct).length;const by={};details.forEach(x=>{by[x.discipline]??={total:0,correct:0};by[x.discipline].total++;if(x.correct)by[x.discipline].correct++});const out={examId:active.id,at:new Date().toISOString(),total:details.length,correct:correctCount,accuracy:Math.round(correctCount/details.length*100),details,byDiscipline:by};setResult(out);const h=load(HISTORY,[]);localStorage.setItem(HISTORY,JSON.stringify([...h,out]));}
return <section className="page sim-page"><div className="sim-heading"><div><div className="page-eyebrow">CARTÃO-RESPOSTA INTELIGENTE</div><h1>Gabarito OMR</h1><p>Baixe o cartão, responda no papel e fotografe para correção automática.</p></div><div className="sim-heading-icon"><ScanLine size={28}/></div></div>{active&&<div className="sim-profile-note"><strong>Simulado vinculado:</strong> {active.title||"Simulado"} · código <b>{active.id}</b> · {active.questions.length} questões. A foto será comparada somente com este gabarito.</div>}<div className="sim-builder"><div className="sim-builder-head"><div><strong>Modelo SEDUC/CE 2026 · 80 questões</strong><span>4 alternativas por questão · A, B, C e D · marcadores para alinhamento</span></div></div><div className="sim-profile-note"><strong>Como usar:</strong> imprima em A4 sem redimensionar, preencha completamente uma única bolha por questão, fotografe a folha inteira e confira a leitura antes da correção.</div><div className="sim-builder-actions"><button className="sim-download" onClick={()=>generateAnswerSheetPdf({title:active?.title||"SIMULADO SEDUC/CE 2026",questions:active?.questions?.length||80})}><Download size={18}/> Baixar cartão-resposta PDF</button></div></div><AnswerSheetScanner questions={active?.questions?.length||80} onApply={correct}/>{read&&!active&&<div className="sim-builder"><strong>Leitura confirmada</strong><p>{read.filter(r=>r.selected!==null).length} respostas reconhecidas. Para corrigir automaticamente, gere primeiro um simulado para vincular o cartão ao gabarito.</p></div>}{result&&<><div className="sim-result-hero"><Trophy size={34}/><div><div className="page-eyebrow">CORREÇÃO DO CARTÃO</div><h1>{result.correct}/{result.total} acertos</h1><p>Desempenho: <strong>{result.accuracy}%</strong> · código do simulado: <strong>{result.examId}</strong></p></div></div><div className="sim-result-grid">{Object.entries(result.byDiscipline).map(([d,r])=><div className="sim-result-card" key={d}><strong>{d}</strong><span>{r.correct}/{r.total} acertos</span><b>{Math.round(r.correct/r.total*100)}%</b></div>)}</div><div className="sim-profile-note"><ShieldCheck size={17}/> Dupla marcação e questão em branco não contam como acerto. A leitura conferida foi salva no histórico local da plataforma.</div></>}</section>}
