import React,{useMemo,useState}from"react";
import{ArrowLeft,ArrowRight,CheckCircle2,ClipboardList,Download,FileText,Play,RotateCcw,ShieldCheck,SlidersHorizontal,Trophy}from"lucide-react";
import{jsPDF}from"jspdf";
import{ALL_QUESTIONS}from"../data/questionSources";
import QuestionMedia from"../components/questions/QuestionMedia";
import AnswerSheetScanner from"../components/simulations/AnswerSheetScanner";
import{generateAnswerSheetPdf}from"../utils/answerSheet";
import"../styles/simulados.css";

const STORAGE_KEY="pdf-concurso-edu-state-v1";
const DRAW_KEY="pdf-concurso-edu-simulation-draw-v4";
const SESSION_KEY="pdf-concurso-edu-active-paper-exam-v1";
const OFFICIAL={title:"SEDUC/CE 2026 — Professor",edital:"Edital nº 014/2026-SEDUC/SEPLAG",duration:"4h30",blocks:[
 {key:"ped",label:"Educação Brasileira: Temas Educacionais e Pedagógicos",count:8,min:3},
 {key:"adm",label:"Administração Pública",count:8,min:3},
 {key:"por",label:"Língua Portuguesa",count:8,min:3},
 {key:"ind",label:"Leitura e Interpretação de Dados e Indicadores Educacionais",count:6,min:2},
 {key:"esp",label:"Conhecimentos Específicos — Filosofia",count:50,min:20}
],p1Min:12,p2Min:20,totalMin:40};
function norm(v=""){return String(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}
function officialKey(d=""){const s=norm(d);if(s.includes("administracao publica"))return"adm";if(s.includes("lingua portuguesa"))return"por";if(s.includes("indicador")||s.includes("interpretacao de dados"))return"ind";if(s.includes("filosofia"))return"esp";if(s.includes("educacao brasileira")||s.includes("pedagog"))return"ped";return null}
function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function loadPlatform(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{}}catch{return{}}}
function loadDraw(){try{return JSON.parse(localStorage.getItem(DRAW_KEY))||{used:{}}}catch{return{used:{}}}}
function saveDraw(v){localStorage.setItem(DRAW_KEY,JSON.stringify(v))}
function formatDuration(seconds=0){const s=Math.max(0,Math.round(seconds)),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return h?`${h}h ${m}min ${sec}s`:m?`${m}min ${sec}s`:`${sec}s`}
function permuteOptions(q){const indexed=(q.options||[]).map((text,originalIndex)=>({text,originalIndex}));let mixed=shuffle(indexed);if(mixed.length>1&&mixed.every((x,i)=>x.originalIndex===i))mixed=[...mixed.slice(1),mixed[0]];return{...q,options:mixed.map(x=>x.text),answer:mixed.findIndex(x=>x.originalIndex===q.answer),optionPermutation:mixed.map(x=>x.originalIndex),instanceId:`${q.id}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}}
function draw(pool,count,used=[]){const usedSet=new Set(used.map(String)),fresh=shuffle(pool.filter(q=>!usedSet.has(String(q.id)))),selected=fresh.slice(0,count);if(selected.length<count){const inExam=new Set(selected.map(q=>String(q.id)));selected.push(...shuffle(pool.filter(q=>!inExam.has(String(q.id)))).slice(0,count-selected.length))}return{selected,used:[...new Set([...used,...selected.map(q=>String(q.id))])]}}
function buildOfficial(){const state=loadDraw(),next={...(state.used||{})},exam=[];for(const b of OFFICIAL.blocks){const pool=ALL_QUESTIONS.filter(q=>officialKey(q.discipline)===b.key&&Array.isArray(q.options)&&q.options.length===4);const d=draw(pool,b.count,next[b.key]||[]);if(d.selected.length<b.count)return{exam:[],error:`Banco insuficiente em ${b.label}: ${d.selected.length}/${b.count}.`};next[b.key]=d.used;exam.push(...d.selected.map(q=>permuteOptions({...q,officialBlock:b.key,officialLabel:b.label})))}saveDraw({used:next});return{exam,error:""}}
function buildCustom(disciplines,counts){let selected=[];for(const d of disciplines){const n=Number(counts[d]||0);if(n)selected.push(...shuffle(ALL_QUESTIONS.filter(q=>q.discipline===d)).slice(0,n))}return shuffle(selected.map(permuteOptions))}
function profile(rows){const blocks=OFFICIAL.blocks.map(b=>{const r=rows.filter(a=>a.officialBlock===b.key),correct=r.filter(a=>a.correct).length;return{...b,total:r.length,correct,passed:correct>=b.min}}),p1=blocks.filter(b=>b.key!=="esp").reduce((s,b)=>s+b.correct,0),p2=blocks.find(b=>b.key==="esp")?.correct||0,total=p1+p2;return{blocks,p1,p2,total,p1Passed:p1>=OFFICIAL.p1Min,p2Passed:p2>=OFFICIAL.p2Min,totalPassed:total>=OFFICIAL.totalMin,passed:blocks.every(b=>b.passed)&&p1>=OFFICIAL.p1Min&&p2>=OFFICIAL.p2Min&&total>=OFFICIAL.totalMin}}
function saveSimulation(result,mode){const s=loadPlatform(),now=new Date().toISOString(),answers=[...(s.answers||[]),...result.answers.map(a=>({...a,at:now,simulation:true}))],history=[...(s.simulationHistory||[]),{id:Date.now(),at:now,type:mode,total:result.total,correct:result.correct,accuracy:result.accuracy,durationSeconds:result.durationSeconds,byDiscipline:result.byDiscipline,officialProfile:result.officialProfile,questionIds:result.answers.map(a=>a.questionId)}];localStorage.setItem(STORAGE_KEY,JSON.stringify({...s,answers,simulations:Number(s.simulations||0)+1,simulationHistory:history}));window.dispatchEvent(new Event("pdfedu-state"))}
function examCode(exam){const raw=exam.map(q=>q.id).join("|");let h=0;for(let i=0;i<raw.length;i++)h=(h*31+raw.charCodeAt(i))>>>0;return`SE26-${h.toString(36).toUpperCase().padStart(6,"0").slice(-6)}`}

export default function Simulados(){
 const disciplines=useMemo(()=>[...new Set(ALL_QUESTIONS.map(q=>q.discipline).filter(Boolean))].sort(),[]),available=useMemo(()=>Object.fromEntries(disciplines.map(d=>[d,ALL_QUESTIONS.filter(q=>q.discipline===d).length])),[disciplines]),officialAvailability=useMemo(()=>Object.fromEntries(OFFICIAL.blocks.map(b=>[b.key,ALL_QUESTIONS.filter(q=>officialKey(q.discipline)===b.key&&q.options?.length===4).length])),[]),officialReady=OFFICIAL.blocks.every(b=>(officialAvailability[b.key]||0)>=b.count);
 const[mode,setMode]=useState("official"),[counts,setCounts]=useState({}),[exam,setExam]=useState([]),[answers,setAnswers]=useState({}),[index,setIndex]=useState(0),[finished,setFinished]=useState(false),[saved,setSaved]=useState(false),[startedAt,setStartedAt]=useState(null),[finishedAt,setFinishedAt]=useState(null),[pdfLoading,setPdfLoading]=useState(false),[pdfError,setPdfError]=useState(""),[builderError,setBuilderError]=useState(""),[paperMode,setPaperMode]=useState(false);
 const totalRequested=Object.values(counts).reduce((a,b)=>a+(Number(b)||0),0),code=exam.length?examCode(exam):"";
 function resetRun(selected,selectedMode){if(!selected.length)return;const now=Date.now();setMode(selectedMode);setExam(selected);setAnswers({});setIndex(0);setFinished(false);setSaved(false);setStartedAt(now);setFinishedAt(null);setPdfError("");setBuilderError("");setPaperMode(false);localStorage.setItem(SESSION_KEY,JSON.stringify({code:examCode(selected),mode:selectedMode,createdAt:now,questionIds:selected.map(q=>q.id),answerKey:selected.map(q=>q.answer)}))}
 function setCount(d,v){setCounts(c=>({...c,[d]:Math.max(0,Math.min(Number(v)||0,available[d]||0))}))}
 function generateOfficial(){const b=buildOfficial();if(b.error){setBuilderError(b.error);return}resetRun(b.exam,"official")}
 function generateCustom(){resetRun(buildCustom(disciplines,counts),"custom")}
 function choose(i){if(!finished)setAnswers(a=>({...a,[exam[index].instanceId]:i}))}
 function applyScan(rows){const mapped={};rows.forEach((r,i)=>{if(i<exam.length&&r.status==="marked"&&Number.isInteger(r.selected))mapped[exam[i].instanceId]=r.selected});setAnswers(a=>({...a,...mapped}));setPaperMode(false);setIndex(0);window.scrollTo({top:0,behavior:"smooth"})}
 function buildResult(end=finishedAt||Date.now()){const rows=exam.map(q=>({questionId:q.id,instanceId:q.instanceId,discipline:q.discipline,topic:q.topic,officialBlock:q.officialBlock,officialLabel:q.officialLabel,selected:answers[q.instanceId],answer:q.answer,correct:answers[q.instanceId]===q.answer,optionPermutation:q.optionPermutation})),correct=rows.filter(a=>a.correct).length,byDiscipline={};rows.forEach(a=>{const l=a.officialLabel||a.discipline;byDiscipline[l]??={total:0,correct:0};byDiscipline[l].total++;if(a.correct)byDiscipline[l].correct++});return{answers:rows,total:exam.length,correct,accuracy:exam.length?Math.round(correct/exam.length*100):0,byDiscipline,durationSeconds:startedAt?Math.max(0,Math.round((end-startedAt)/1000)):0,officialProfile:mode==="official"?profile(rows):null}}
 function finish(){if(!exam.length)return;const end=Date.now();setFinishedAt(end);setFinished(true);const r=buildResult(end);saveSimulation(r,mode);setSaved(true);window.scrollTo({top:0,behavior:"smooth"})}
 function downloadSheet(){generateAnswerSheetPdf({title:`${mode==="official"?OFFICIAL.title:"Simulado personalizado"} · Código ${code}`,questions:Math.min(exam.length,80)})}
 function downloadExam(){if(!exam.length)return;setPdfLoading(true);setPdfError("");try{const doc=new jsPDF({unit:"mm",format:"a4"}),margin=15,w=180,h=297;let y=18;const ensure=n=>{if(y+n>282){doc.addPage();y=18}},text=(t,size=10,bold=false,space=3)=>{doc.setFont("helvetica",bold?"bold":"normal");doc.setFontSize(size);const lines=doc.splitTextToSize(String(t||""),w);ensure(lines.length*4+space);doc.text(lines,margin,y);y+=lines.length*4+space};doc.setFont("helvetica","bold");doc.setFontSize(18);doc.text("PDF CONCURSO EDU",105,18,{align:"center"});doc.setFontSize(13);doc.text(mode==="official"?OFFICIAL.title:"SIMULADO PERSONALIZADO",105,27,{align:"center"});doc.setFontSize(9);doc.text(`Código da prova: ${code}`,105,34,{align:"center"});y=45;text("INSTRUÇÕES AO CANDIDATO",12,true,4);["Confira se o caderno contém todas as questões e quatro alternativas (A, B, C e D).","Marque apenas uma alternativa por questão no cartão-resposta.","Marcações duplas ou rasuradas devem ser conferidas antes da correção por foto.",`Tempo recomendado para esta simulação: ${OFFICIAL.duration}.`,`A correção eletrônica usa o código desta prova para associar o cartão ao gabarito correto.`].forEach(x=>text(`• ${x}`,9,false,2));if(mode==="official"){y+=3;text("ESTRUTURA DO EDITAL",11,true,3);OFFICIAL.blocks.forEach(b=>text(`${b.label}: ${b.count} questões · mínimo ${b.min} acertos`,8.5,false,2));text(`P1: mínimo ${OFFICIAL.p1Min}/30 · P2: mínimo ${OFFICIAL.p2Min}/50 · Total: mínimo ${OFFICIAL.totalMin}/80`,8.5,true,4)}doc.addPage();y=18;exam.forEach((q,i)=>{ensure(26);text(`QUESTÃO ${String(i+1).padStart(2,"0")} — ${q.officialLabel||q.discipline}${q.topic?` · ${q.topic}`:""}`,10,true,3);if(q.context)text(q.context,8.5,false,3);text(q.originalStatement||q.statement,9.5,false,3);(q.options||[]).forEach((o,oi)=>text(`${String.fromCharCode(65+oi)}) ${o}`,9,false,2));y+=3});doc.save(`Prova_${code}.pdf`)}catch(e){setPdfError(`Não foi possível gerar a prova: ${e?.message||"erro desconhecido"}`)}finally{setPdfLoading(false)}}
 function downloadReport(){if(!finished)return;setPdfLoading(true);setPdfError("");try{const r=buildResult(),doc=new jsPDF({unit:"mm",format:"a4"}),margin=15,w=180;let y=18;const ensure=n=>{if(y+n>282){doc.addPage();y=18}},text=(t,size=10,bold=false,space=3)=>{doc.setFont("helvetica",bold?"bold":"normal");doc.setFontSize(size);const lines=doc.splitTextToSize(String(t||""),w);ensure(lines.length*4+space);doc.text(lines,margin,y);y+=lines.length*4+space};doc.setFont("helvetica","bold");doc.setFontSize(18);doc.text("RELATÓRIO DO SIMULADO",105,18,{align:"center"});doc.setFontSize(10);doc.text(`Código ${code}`,105,25,{align:"center"});y=36;text(`${r.correct}/${r.total} acertos · ${r.accuracy}% · Tempo ${formatDuration(r.durationSeconds)}`,13,true,5);Object.entries(r.byDiscipline).forEach(([d,v])=>text(`${d}: ${v.correct}/${v.total} (${Math.round(v.correct/v.total*100)}%)`,9,false,2));if(r.officialProfile){y+=4;text("PERFIS MÍNIMOS DO EDITAL",11,true,3);r.officialProfile.blocks.forEach(b=>text(`${b.passed?"ATINGIU":"NÃO ATINGIU"} — ${b.label}: ${b.correct}/${b.total} · mínimo ${b.min}`,8.5,false,2));text(`P1 ${r.officialProfile.p1}/30 · P2 ${r.officialProfile.p2}/50 · Total ${r.officialProfile.total}/80`,9,true,3)}doc.addPage();y=18;exam.forEach((q,i)=>{const s=answers[q.instanceId],ok=s===q.answer;ensure(18);text(`Questão ${i+1}: ${ok?"ACERTO":"ERRO"} · marcada ${s===undefined?"—":String.fromCharCode(65+s)} · gabarito ${String.fromCharCode(65+q.answer)}`,9,true,2);if(q.explanation)text(q.explanation,8,false,3)});doc.save(`Relatorio_${code}.pdf`)}catch(e){setPdfError(`Não foi possível gerar o relatório: ${e?.message||"erro desconhecido"}`)}finally{setPdfLoading(false)}}
 const result=finished?buildResult():null,current=exam[index],answered=Object.keys(answers).length;
 if(!exam.length)return <section className="page sim-page"><div className="sim-heading"><div><div className="page-eyebrow">GERADOR DE SIMULADOS</div><h1>Simulados</h1><p>Monte uma prova digital ou para impressão, com cartão-resposta e correção por foto.</p></div><div className="sim-heading-icon"><ClipboardList size={28}/></div></div><div className="sim-mode-grid"><button className={`sim-mode-card ${mode==="official"?"active":""}`} onClick={()=>setMode("official")}><ShieldCheck size={24}/><strong>Simulado oficial SEDUC 2026</strong><span>80 questões na ordem do edital e análise dos mínimos eliminatórios.</span></button><button className={`sim-mode-card ${mode==="custom"?"active":""}`} onClick={()=>setMode("custom")}><SlidersHorizontal size={24}/><strong>Criar meu simulado</strong><span>Escolha disciplinas e quantidade.</span></button></div>{mode==="official"?<div className="sim-builder"><div className="sim-builder-head"><div><strong>{OFFICIAL.title}</strong><span>{OFFICIAL.edital} · P1 30 + P2 50 = 80</span></div><div className="sim-total"><span>Total</span><strong>80</strong></div></div><div className="sim-official-table">{OFFICIAL.blocks.map(b=><div className="sim-official-row" key={b.key}><div><strong>{b.label}</strong><span>{officialAvailability[b.key]||0} compatíveis no banco</span></div><b>{b.count}</b><em>mín. {b.min}</em></div>)}</div>{builderError&&<div className="sim-builder-error">{builderError}</div>}<div className="sim-builder-actions"><button className="sim-generate" disabled={!officialReady} onClick={generateOfficial}><Play size={18}/> Montar prova oficial</button></div></div>:<div className="sim-builder"><div className="sim-discipline-list">{disciplines.map(d=><div className="sim-discipline-row" key={d}><div><strong>{d}</strong><span>{available[d]} disponíveis</span></div><input type="number" min="0" max={available[d]} value={counts[d]||""} onChange={e=>setCount(d,e.target.value)}/></div>)}</div><div className="sim-builder-actions"><button className="sim-clear" onClick={()=>setCounts({})}><RotateCcw size={17}/> Limpar</button><button className="sim-generate" disabled={!totalRequested} onClick={generateCustom}><Play size={18}/> Sortear ({totalRequested})</button></div></div>}</section>;
 if(finished)return <section className="page sim-page"><div className="sim-result-hero"><Trophy size={34}/><div><div className="page-eyebrow">RESULTADO</div><h1>{result.correct}/{result.total} acertos</h1><p>{result.accuracy}% · {formatDuration(result.durationSeconds)}{saved?" · salvo no histórico":""}</p></div></div>{result.officialProfile&&<div className={`sim-official-verdict ${result.officialProfile.passed?"passed":"failed"}`}><ShieldCheck size={24}/><div><strong>{result.officialProfile.passed?"Perfis mínimos atingidos":"Atenção aos mínimos do edital"}</strong><span>P1 {result.officialProfile.p1}/30 · P2 {result.officialProfile.p2}/50 · total {result.officialProfile.total}/80</span></div></div>}<div className="sim-report-actions"><button className="sim-download" onClick={downloadReport} disabled={pdfLoading}><Download size={18}/> Baixar relatório PDF</button><button className="sim-download" onClick={downloadExam}><FileText size={18}/> Baixar prova novamente</button><button className="sim-download" onClick={downloadSheet}><ClipboardList size={18}/> Baixar cartão-resposta</button>{pdfError&&<span className="sim-pdf-error">{pdfError}</span>}</div><div className="sim-result-grid">{Object.entries(result.byDiscipline).map(([d,r])=><div className="sim-result-card" key={d}><strong>{d}</strong><span>{r.correct}/{r.total} acertos</span><b>{Math.round(r.correct/r.total*100)}%</b></div>)}</div><button className="sim-new" onClick={()=>setExam([])}><RotateCcw size={17}/> Novo simulado</button></section>;
 return <section className="page sim-page"><div className="sim-running-head"><button onClick={()=>setExam([])}><ArrowLeft size={17}/> Sair</button><div><strong>{mode==="official"?"Simulado oficial SEDUC 2026":"Simulado personalizado"}</strong><span>Código {code} · {answered}/{exam.length} respondidas</span></div><button className="sim-finish" onClick={finish}>Finalizar</button></div><div className="sim-report-actions"><button className="sim-download" onClick={downloadExam} disabled={pdfLoading}><FileText size={18}/> Baixar prova PDF</button><button className="sim-download" onClick={downloadSheet}><ClipboardList size={18}/> Baixar cartão-resposta</button><button className="sim-download" onClick={()=>setPaperMode(v=>!v)}><ClipboardList size={18}/> {paperMode?"Fechar leitura":"Corrigir gabarito por foto"}</button></div>{paperMode&&<AnswerSheetScanner questions={Math.min(exam.length,80)} onApply={applyScan}/>}<article className="sim-question-card"><header><div><strong>Questão {index+1} de {exam.length}</strong><span>{current.officialLabel||current.discipline} · {current.topic||""}</span></div><span>{Math.round((index+1)/exam.length*100)}%</span></header>{current.context&&<div className="sim-context"><b>TEXTO-BASE</b><p>{current.context}</p></div>}<QuestionMedia media={current.media}/><div className="sim-statement">{current.originalStatement||current.statement}</div><div className="sim-options">{current.options.map((o,i)=><button key={`${current.instanceId}-${i}`} onClick={()=>choose(i)} className={answers[current.instanceId]===i?"selected":""}><span>{String.fromCharCode(65+i)}</span><p>{o}</p>{answers[current.instanceId]===i&&<CheckCircle2 size={19}/>}</button>)}</div><div className="sim-nav"><button disabled={index===0} onClick={()=>setIndex(i=>Math.max(0,i-1))}><ArrowLeft size={17}/> Anterior</button><div>{exam.map((q,i)=><button key={q.instanceId} className={`${i===index?"current":""} ${answers[q.instanceId]!==undefined?"answered":""}`} onClick={()=>setIndex(i)}>{i+1}</button>)}</div><button disabled={index===exam.length-1} onClick={()=>setIndex(i=>Math.min(exam.length-1,i+1))}>Próxima <ArrowRight size={17}/></button></div></article></section>
}
