import React,{useMemo,useState}from"react";
import{ArrowLeft,ArrowRight,CheckCircle2,ClipboardList,Play,RotateCcw,Trophy}from"lucide-react";
import{ALL_QUESTIONS}from"../data/questionSources";
import"../styles/simulados.css";

const STORAGE_KEY="pdf-concurso-edu-state-v1";
function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function loadPlatform(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{}}catch{return{}}}
function saveSimulation(result){const s=loadPlatform();const answers=[...(s.answers||[]),...result.answers.map(a=>({...a,at:new Date().toISOString(),simulation:true}))];const history=[...(s.simulationHistory||[]),{id:Date.now(),at:new Date().toISOString(),total:result.total,correct:result.correct,accuracy:result.accuracy,byDiscipline:result.byDiscipline}];localStorage.setItem(STORAGE_KEY,JSON.stringify({...s,answers,simulations:Number(s.simulations||0)+1,simulationHistory:history}));window.dispatchEvent(new Event("pdfedu-state"))}

export default function Simulados(){
 const disciplines=useMemo(()=>[...new Set(ALL_QUESTIONS.map(q=>q.discipline).filter(Boolean))].sort(),[]);
 const available=useMemo(()=>Object.fromEntries(disciplines.map(d=>[d,ALL_QUESTIONS.filter(q=>q.discipline===d).length])),[disciplines]);
 const [counts,setCounts]=useState({});const [exam,setExam]=useState([]);const [answers,setAnswers]=useState({});const [index,setIndex]=useState(0);const [finished,setFinished]=useState(false);const [saved,setSaved]=useState(false);
 const totalRequested=Object.values(counts).reduce((a,b)=>a+(Number(b)||0),0);
 function setCount(d,value){const n=Math.max(0,Math.min(Number(value)||0,available[d]||0));setCounts(c=>({...c,[d]:n}))}
 function generate(){const selected=[];for(const d of disciplines){const n=Number(counts[d]||0);if(n>0)selected.push(...shuffle(ALL_QUESTIONS.filter(q=>q.discipline===d)).slice(0,n))}if(!selected.length)return;setExam(shuffle(selected));setAnswers({});setIndex(0);setFinished(false);setSaved(false)}
 function choose(i){if(!finished)setAnswers(a=>({...a,[exam[index].id]:i}))}
 function finish(){if(!exam.length)return;setFinished(true);const result=buildResult();saveSimulation(result);setSaved(true);window.scrollTo({top:0,behavior:"smooth"})}
 function buildResult(){const answerRows=exam.map(q=>({questionId:q.id,discipline:q.discipline,topic:q.topic,selected:answers[q.id],answer:q.answer,correct:answers[q.id]===q.answer}));const correct=answerRows.filter(a=>a.correct).length;const byDiscipline={};answerRows.forEach(a=>{byDiscipline[a.discipline]??={total:0,correct:0};byDiscipline[a.discipline].total++;if(a.correct)byDiscipline[a.discipline].correct++});return{answers:answerRows,total:exam.length,correct,accuracy:exam.length?Math.round(correct/exam.length*100):0,byDiscipline}}
 const result=finished?buildResult():null;const current=exam[index];
 if(!exam.length)return <section className="page sim-page"><div className="sim-heading"><div><div className="page-eyebrow">GERADOR DE SIMULADOS</div><h1>Simulado aleatório</h1><p>Escolha as disciplinas e quantas questões deseja em cada uma.</p></div><div className="sim-heading-icon"><ClipboardList size={28}/></div></div><div className="sim-builder"><div className="sim-builder-head"><div><strong>Monte seu simulado</strong><span>{ALL_QUESTIONS.length} questões auditadas disponíveis</span></div><div className="sim-total"><span>Total escolhido</span><strong>{totalRequested}</strong></div></div><div className="sim-discipline-list">{disciplines.map(d=><div className="sim-discipline-row" key={d}><div><strong>{d}</strong><span>{available[d]} disponíveis</span></div><input type="number" min="0" max={available[d]} value={counts[d]||""} placeholder="0" onChange={e=>setCount(d,e.target.value)}/></div>)}</div><div className="sim-builder-actions"><button type="button" className="sim-clear" onClick={()=>setCounts({})}><RotateCcw size={17}/> Limpar</button><button type="button" className="sim-generate" disabled={!totalRequested} onClick={generate}><Play size={18}/> Gerar simulado ({totalRequested})</button></div></div></section>;
 if(finished)return <section className="page sim-page"><div className="sim-result-hero"><Trophy size={34}/><div><div className="page-eyebrow">RESULTADO DO SIMULADO</div><h1>{result.correct}/{result.total} acertos</h1><p>Desempenho geral: <strong>{result.accuracy}%</strong>{saved?" · resultado salvo no Dashboard":""}</p></div></div><div className="sim-result-grid">{Object.entries(result.byDiscipline).map(([d,r])=><div className="sim-result-card" key={d}><strong>{d}</strong><span>{r.correct}/{r.total} acertos</span><b>{Math.round(r.correct/r.total*100)}%</b></div>)}</div><div className="sim-review-list">{exam.map((q,i)=>{const selected=answers[q.id],ok=selected===q.answer;return <article className={`sim-review ${ok?"ok":"wrong"}`} key={`${q.id}-${i}`}><header><strong>Questão {i+1}</strong><span>{q.discipline} · {q.topic}</span></header>{q.context&&<div className="sim-context">{q.context}</div>}<p>{q.statement}</p><div className="sim-review-answer"><span>Você marcou: {selected===undefined?"Não respondida":String.fromCharCode(65+selected)}</span><strong>Gabarito: {String.fromCharCode(65+q.answer)}</strong></div>{q.explanation&&<small>{q.explanation}</small>}</article>})}</div><button className="sim-new" onClick={()=>{setExam([]);setFinished(false);setAnswers({});setCounts({})}}><RotateCcw size={17}/> Criar novo simulado</button></section>;
 const answeredCount=Object.keys(answers).length;
 return <section className="page sim-page"><div className="sim-running-head"><button onClick={()=>setExam([])}><ArrowLeft size={17}/> Sair</button><div><strong>Simulado em andamento</strong><span>{answeredCount}/{exam.length} respondidas</span></div><button className="sim-finish" onClick={finish}>Finalizar</button></div><article className="sim-question-card"><header><div><strong>Questão {index+1} de {exam.length}</strong><span>{current.discipline} · {current.topic}</span></div><span>{Math.round(((index+1)/exam.length)*100)}%</span></header>{current.context&&<div className="sim-context"><b>TEXTO-BASE</b><p>{current.context}</p></div>}<div className="sim-statement">{current.statement}</div><div className="sim-options">{current.options.map((o,i)=><button type="button" key={i} onClick={()=>choose(i)} className={answers[current.id]===i?"selected":""}><span>{String.fromCharCode(65+i)}</span><p>{o}</p>{answers[current.id]===i&&<CheckCircle2 size={19}/>}</button>)}</div><div className="sim-nav"><button disabled={index===0} onClick={()=>setIndex(i=>Math.max(0,i-1))}><ArrowLeft size={17}/> Anterior</button><div>{exam.map((q,i)=><button key={`${q.id}-${i}`} className={`${i===index?"current":""} ${answers[q.id]!==undefined?"answered":""}`} onClick={()=>setIndex(i)}>{i+1}</button>)}</div><button disabled={index===exam.length-1} onClick={()=>setIndex(i=>Math.min(exam.length-1,i+1))}>Próxima <ArrowRight size={17}/></button></div></article></section>
}
