import{jsPDF}from"jspdf";
import{downloadPdfDocument}from"./pdfDownload";

export const OMR={questions:80,choices:4,cols:4,rows:20};
export function generateAnswerSheetPdf({title="SEDUC/CE 2026 — PROFESSOR",subtitle="PDF CONCURSO EDU",questions=80,code="",paperType=1}={}){
 const doc=new jsPDF({unit:"mm",format:"a4"}),letters=["A","B","C","D"],colX=[18,67,116,165],startY=70,rowH=9.35,type=Math.min(4,Math.max(1,Number(paperType)||1));
 doc.setDrawColor(0);doc.setTextColor(0);doc.setLineWidth(.25);[[7,7],[199,7],[7,286],[199,286]].forEach(([x,y])=>doc.rect(x,y,4,4,"F"));
 doc.setFont("helvetica","bold");doc.setFontSize(16);doc.text(subtitle,105,15,{align:"center"});doc.setFontSize(11);doc.text(title,105,22,{align:"center",maxWidth:170});doc.setFont("helvetica","normal");doc.setFontSize(7.5);doc.text("CARTÃO-RESPOSTA · DOCUMENTO DE CORREÇÃO",105,28,{align:"center"});doc.line(15,32,195,32);
 doc.setFont("helvetica","bold");doc.setFontSize(8.2);doc.text(`PROVA TIPO ${type}`,15,38);doc.text(`CÓDIGO: ${code||"________________"}`,70,38);doc.text("DATA: ____/____/______",195,38,{align:"right"});doc.setFont("helvetica","normal");doc.setFontSize(7.8);doc.text("NOME DO CANDIDATO",15,45);doc.line(15,51,129,51);doc.text("ASSINATURA",137,45);doc.line(137,51,195,51);
 doc.setFont("helvetica","bold");doc.setFontSize(7.2);doc.text("INSTRUÇÕES",15,57);doc.setFont("helvetica","normal");doc.setFontSize(6.7);doc.text("Confira o TIPO DA PROVA e o CÓDIGO antes de preencher. Use caneta azul ou preta e marque totalmente apenas uma bolha por questão.",15,62,{maxWidth:178});doc.setFontSize(6.4);doc.text("CORRETO",151,57);doc.circle(166,55.8,2.1);doc.circle(166,55.8,1.45,"F");doc.text("INCORRETO",174,57);doc.circle(191,55.8,2.1);doc.line(189.5,54.3,192.5,57.3);doc.line(192.5,54.3,189.5,57.3);doc.line(15,66,195,66);
 for(let c=0;c<4;c++){doc.setFont("helvetica","bold");doc.setFontSize(6.8);letters.forEach((l,i)=>doc.text(l,colX[c]+15+i*7.1,startY-4,{align:"center"}));for(let r=0;r<20;r++){const n=c*20+r+1;if(n>questions)continue;const y=startY+r*rowH;doc.setFont("helvetica","bold");doc.setFontSize(6.8);doc.text(String(n).padStart(2,"0"),colX[c],y+.9);letters.forEach((l,i)=>{const x=colX[c]+15+i*7.1;doc.circle(x,y,2.3);doc.setFont("helvetica","normal");doc.setFontSize(5.2);doc.text(l,x,y+.85,{align:"center"})})}}
 doc.line(15,262,195,262);doc.setFont("helvetica","bold");doc.setFontSize(6.7);doc.text("ATENÇÃO",15,268);doc.setFont("helvetica","normal");doc.text("A correção depende do tipo de prova informado. Marcações múltiplas, rasuras ou tipo incorreto podem alterar o resultado.",30,268,{maxWidth:165});doc.setFontSize(6.1);doc.text("Não cubra os quatro marcadores pretos dos cantos: eles auxiliam a leitura digital do cartão-resposta.",105,276,{align:"center",maxWidth:180});doc.setFont("helvetica","bold");doc.setFontSize(6);doc.text(`PDF CONCURSO EDU · PROVA TIPO ${type} · ${code||"SEM CÓDIGO"}`,105,287,{align:"center"});
 return downloadPdfDocument(doc,`Cartao_Resposta_${code||"SEDUC_2026"}_Tipo_${type}.pdf`);
}
function gray(d,i){return(d[i]+d[i+1]+d[i+2])/3}
async function loadBitmap(file){if(typeof createImageBitmap==="function")return createImageBitmap(file);const url=URL.createObjectURL(file);try{const img=await new Promise((ok,fail)=>{const el=new Image();el.onload=()=>ok(el);el.onerror=fail;el.src=url});return img}finally{URL.revokeObjectURL(url)}}
function markerIn(img,W,H,x0,y0,x1,y1){let sx=0,sy=0,n=0;for(let y=Math.floor(y0*H);y<Math.floor(y1*H);y+=2)for(let x=Math.floor(x0*W);x<Math.floor(x1*W);x+=2){const i=(y*W+x)*4;if(gray(img.data,i)<55){sx+=x;sy+=y;n++}}return n>20?{x:sx/n,y:sy/n,n}:null}
function mapQuad(tl,tr,bl,br,u,v){return{x:(1-u)*(1-v)*tl.x+u*(1-v)*tr.x+(1-u)*v*bl.x+u*v*br.x,y:(1-u)*(1-v)*tl.y+u*(1-v)*tr.y+(1-u)*v*bl.y+u*v*br.y}}
export async function readAnswerSheetImage(file,{questions=80}={}){const bitmap=await loadBitmap(file),canvas=document.createElement("canvas"),max=1800,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const ctx=canvas.getContext("2d",{willReadFrequently:true});ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);const img=ctx.getImageData(0,0,canvas.width,canvas.height),W=canvas.width,H=canvas.height;
 const tl=markerIn(img,W,H,0,.0,.18,.18),tr=markerIn(img,W,H,.82,0,1,.18),bl=markerIn(img,W,H,0,.82,.18,1),br=markerIn(img,W,H,.82,.82,1,1);if(!tl||!tr||!bl||!br)throw new Error("Não foi possível localizar os quatro marcadores pretos. Fotografe a folha inteira, sem cortar os cantos.");
 // Coordenadas normalizadas em relação aos centros dos marcadores impressos (9 mm/201 mm horizontal; 9 mm/288 mm vertical).
 const markerLeft=9/210,markerRight=201/210,markerTop=9/297,markerBottom=288/297;
 const norm=(x,y)=>({u:(x/210-markerLeft)/(markerRight-markerLeft),v:(y/297-markerTop)/(markerBottom-markerTop)}),colX=[18,67,116,165],startY=70,rowH=9.35,answers=[];
 for(let q=0;q<questions;q++){const c=Math.floor(q/20),r=q%20,scores=[];for(let a=0;a<4;a++){const p=norm(colX[c]+15+a*7.1,startY+r*rowH),center=mapQuad(tl,tr,bl,br,p.u,p.v),rad=Math.max(4,Math.min(W,H)*.0065);let dark=0,total=0;for(let yy=Math.floor(center.y-rad);yy<=center.y+rad;yy++)for(let xx=Math.floor(center.x-rad);xx<=center.x+rad;xx++){if(xx<0||yy<0||xx>=W||yy>=H)continue;const dx=xx-center.x,dy=yy-center.y;if(dx*dx+dy*dy>rad*rad*.58)continue;total++;if(gray(img.data,(yy*W+xx)*4)<135)dark++}scores.push(total?dark/total:0)}const ranked=scores.map((s,i)=>({s,i})).sort((a,b)=>b.s-a.s),best=ranked[0],second=ranked[1];let status="blank",selected=null;if(best.s>=.30){if(second.s>=.27&&best.s-second.s<.12)status="multiple";else{selected=best.i;status=best.s<.42?"uncertain":"marked"}}answers.push({question:q+1,selected,status,scores})}
 return{answers,preview:canvas.toDataURL("image/jpeg",.82),markers:{tl,tr,bl,br}};
}