import{jsPDF}from"jspdf";
import{sanitizeOCRText,sanitizeQuestionOCR}from"./ocrSanitizer";
import{downloadPdfDocument}from"./pdfDownload";
const clean=sanitizeOCRText,letter=i=>String.fromCharCode(65+i),key=v=>clean(v).toLowerCase().replace(/[^a-zà-ÿ0-9]+/gi," ").trim();
export function generateExamPdf({exam=[],code="",mode="official",official=null,paperType=1}){
 if(!exam.length)throw new Error("Nenhuma questão disponível para gerar a prova.");
 exam=exam.map(sanitizeQuestionOCR);
 const type=Math.min(4,Math.max(1,+paperType||1)),doc=new jsPDF({unit:"mm",format:"a4"}),W=210,M=18,U=174,TOP=18,BOT=276;
 let y=TOP,page=1,block=null,lastContext="";
 const font=(s=9,b=false)=>{doc.setFont("helvetica",b?"bold":"normal");doc.setFontSize(s);doc.setTextColor(25)};
 const header=()=>{font(7.2,true);doc.text("SIMULADO PARA CONCURSO PÚBLICO",M,10);font(6.8);doc.text(`${code} · TIPO ${type}`,W-M,10,{align:"right"});doc.setDrawColor(190);doc.line(M,12,W-M,12)};
 const footer=()=>{font(6.5);doc.setDrawColor(205);doc.line(M,282,W-M,282);doc.text(`PDF CONCURSO EDU · ${code||"SIMULADO"} · TIPO ${type}`,M,287);doc.text(`Página ${page}`,W-M,287,{align:"right"})};
 const next=()=>{footer();doc.addPage();page++;y=TOP;header()},ensure=h=>{if(y+h>BOT)next()};
 const lines=(t,s,w)=>{doc.setFontSize(s);return doc.splitTextToSize(clean(t),w)},height=(t,s,w,lh)=>Math.max(1,lines(t,s,w).length)*lh;
 const write=(t,{size=8.8,bold=false,width=U,x=M,space=2,lh=4.15}={})=>{for(const ln of lines(t,size,width)){if(y+lh>BOT)next();font(size,bold);doc.text(ln,x,y);y+=lh}y+=space};
 const section=t=>{ensure(15);doc.setFillColor(239,241,244);doc.rect(M,y,U,9,"F");font(8.7,true);doc.text(clean(t).toUpperCase(),M+4,y+6);y+=14;lastContext=""};
 const table=m=>{if(!m?.headers?.length)return;const cols=m.headers.length,cw=U/cols,rh=9;if(m.title)write(m.title,{size:8.2,bold:true});ensure(Math.min(55,((m.rows||[]).length+1)*rh+5));const row=(cells,h=false)=>{ensure(rh+1);cells.forEach((v,c)=>{if(h){doc.setFillColor(240);doc.rect(M+c*cw,y,cw,rh,"FD")}else doc.rect(M+c*cw,y,cw,rh);font(6.8,h);doc.text(lines(v,6.8,cw-4).slice(0,2),M+c*cw+2,y+4)});y+=rh};row(m.headers,true);(m.rows||[]).forEach(r=>row(r,false));y+=4};
 const bar=m=>{const d=(m.data||[]).filter(a=>Number.isFinite(+a.value));if(!d.length)return;ensure(58);if(m.title)write(m.title,{size:8.2,bold:true});const x0=M+12,w=U-20,base=y+34,max=Math.max(...d.map(a=>+a.value),1),gap=w/d.length,bw=Math.min(18,gap*.55);doc.line(x0,y,x0,base);doc.line(x0,base,x0+w,base);d.forEach((a,i)=>{const bh=29*(+a.value/max),x=x0+i*gap+(gap-bw)/2;doc.setFillColor(90);doc.rect(x,base-bh,bw,bh,"F");font(6.5,true);doc.text(String(a.displayValue??a.value),x+bw/2,base-bh-1,{align:"center"});font(6.2);doc.text(clean(a.label),x+bw/2,base+4,{align:"center",maxWidth:gap-2})});y=base+10};
 const media=m=>{if(!m)return;if(m.type==="table")table(m);else if(m.type==="bar-chart"||m.type==="bar")bar(m);else if(m.type==="statements"||m.type==="key")(m.items||m.statements||[]).forEach((s,i)=>write(`${i+1}. ${s}`,{size:8,x:M+5,width:U-5,space:1,lh:3.9}))};
 const groups=new Map();exam.forEach((q,i)=>{const k=key(q.context);if(k){if(!groups.has(k))groups.set(k,[]);groups.get(k).push(i+1)}}),ctxLabel=k=>{const n=groups.get(k)||[];return n.length>1?`TEXTO PARA AS QUESTÕES ${n[0]} A ${n[n.length-1]}`:"TEXTO-BASE"};
 doc.setFillColor(26,36,50);doc.rect(0,0,W,30,"F");doc.setTextColor(255);doc.setFont("helvetica","bold");doc.setFontSize(18);doc.text("PDF CONCURSO EDU",105,12,{align:"center"});doc.setFontSize(10.5);doc.text("CADERNO DE PROVA · SIMULADO",105,20,{align:"center"});doc.setFontSize(8);doc.text(`PROVA TIPO ${type}`,105,26,{align:"center"});
 y=40;font(12,true);doc.text(mode==="official"?(official?.title||"SIMULADO OFICIAL"):"SIMULADO PERSONALIZADO",105,y,{align:"center"});y+=7;font(8);doc.text(official?.edital||"",105,y,{align:"center"});y+=7;doc.setDrawColor(120);doc.rect(M,y,U,31);font(8,true);doc.text(`TIPO ${type}`,M+5,y+7);doc.text(`CÓDIGO ${code}`,W-M-5,y+7,{align:"right"});font(7.8);doc.text("Nome: ______________________________________________",M+5,y+15);doc.text("Assinatura: __________________________________________",M+5,y+22);doc.text(`Duração: ${official?.duration||"—"}`,W-M-5,y+15,{align:"right"});doc.text("Data: ____/____/______",W-M-5,y+22,{align:"right"});y+=39;
 write("INSTRUÇÕES",{size:10.5,bold:true,space:3});[`Este caderno contém ${exam.length} questões objetivas, com quatro alternativas e uma única resposta correta.`,`Confira o tipo e o código do caderno antes de iniciar.`,`Verifique a integridade das páginas, textos, tabelas e gráficos.`,`Marque somente uma alternativa por questão no cartão-resposta.`,`Tempo previsto: ${official?.duration||"conforme planejamento"}.`].forEach((t,i)=>write(`${i+1}. ${t}`,{size:8.2,space:1,lh:3.8}));
 if(mode==="official"&&official?.blocks){y+=3;write("DISTRIBUIÇÃO DAS QUESTÕES",{size:9.5,bold:true});official.blocks.forEach(b=>{ensure(7);font(7.4);doc.text(clean(b.label),M+3,y);doc.text(String(b.count),W-M-3,y,{align:"right"});y+=6})}
 footer();doc.addPage();page++;y=TOP;header();
 exam.forEach((q,i)=>{const b=q.officialLabel||q.discipline||"Questões";if(b!==block){section(b);block=b}const ctx=clean(q.context),ck=key(ctx);if(ctx&&ck!==lastContext){ensure(Math.min(42,height(ctx,8.35,U-4,4.15)+12));font(8.1,true);doc.text(ctxLabel(ck),M,y);y+=5.5;write(ctx,{size:8.35,width:U-4,x:M+2,space:5,lh:4.15});lastContext=ck}media(q.media);const st=clean(q.originalStatement||q.statement),opts=(q.options||[]).slice(0,4),x=M+9,qh=7+height(st,8.8,U-9,4.25)+opts.reduce((s,o)=>s+height(o,8.35,U-9,4.05)+1.2,0)+5;if(qh<=BOT-TOP)ensure(qh);else if(y>TOP+8)next();font(8.8,true);doc.text(`${String(i+1).padStart(2,"0")}.`,M,y);write(st,{size:8.8,width:U-9,x,space:2.4,lh:4.25});opts.forEach((o,j)=>write(`${letter(j)}) ${o}`,{size:8.35,width:U-9,x,space:1.35,lh:4.05}));y+=2;ensure(4);doc.setDrawColor(220);doc.line(M,y,W-M,y);y+=5});
 footer();return downloadPdfDocument(doc,`Prova_${code||"Simulado"}_Tipo_${type}.pdf`);
}
